version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: circleci/postgres:11.6-alpine
        environment:
          POSTGRES_DB: larasns
          POSTGRES_USER: default
          POSTGRES_PASSWORD: secret
    environment:
      APP_ENV: testing
      DB_CONNECTION: pgsql
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: larasns
      DB_USERNAME: default
      DB_PASSWORD: secret
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "./laravel-ci2/composer.lock" }}
      - run: composer install -n --prefer-dist --working-dir=./laravel-ci2/
      - save_cache:
          key: composer-v1-{{ checksum "./laravel-ci2/composer.lock" }}
          paths:
            - ./laravel-ci2/vendor
      - run: yarn install --cwd ./laravel-ci2
      - run: npm run dev --cwd ./laravel-ci2
      - run:
          name: get ready for postgres
          command: |
            sudo apt-get update
            sudo apt-get install libpq-dev
            sudo docker-php-ext-install pdo_pgsql
            dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: php test
          command: php ./laravel-ci2/vendor/bin/phpunit --configuration=./laravel-ci2/phpunit.xml
