version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "./laravel-ci2/composer.lock" }}
      - run: composer install -n --prefer-dist --working-dir=./laravel-ci2/
      - save_cache:
          key: composer-v1-{{ checksum "./laravel-ci2/composer.lock" }}
          paths:
            - ./laravel-ci2/vendor
      - run: php ./laravel-ci2/artisan --env=testing
      - run: php ./laravel-ci2/vendor/bin/phpunit --configuration=./laravel-ci2/phpunit.xml
