version: 0.2

phases:
  install:
    commands:
      - composer install -n --no-dev --prefer-dist --prefer-dist --working-dir=./laravel-ci2/
      - npm ci

  build:
    commands:
      - npm run prod

artifacts:
  files:
    - './**/*'
